FROM deepc/base:p36-cuda9-cudnn7-devel

RUN apt-get update && apt-get install -y --no-install-recommends \
		software-properties-common python-software-properties

#RUN add-apt-repository ppa:fkrull/deadsnakes
RUN apt-get update && apt-get install -y --no-install-recommends \
        openmpi-bin \
        libpng-dev \
        libtiff-dev \
        libpython3.6-dev \
		libjasper-dev && \
    	rm -rf /var/lib/apt/lists/*

ENV KMP_DUPLICATE_LIB_OK TRUE

RUN pip install --upgrade pip && \
    pip install --upgrade https://cntk.ai/PythonWheel/GPU/cntk-2.3-cp36-cp36m-linux_x86_64.whl && \
    conda clean -yt



