FROM deepc/base36

RUN apt-get update && apt-get install -y --no-install-recommends \
        openmpi-bin \
        libpng-dev \
        libtiff-dev \
		libjasper-dev && \
    	rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install https://cntk.ai/PythonWheel/GPU/cntk-2.3-cp36-cp36m-linux_x86_64.whl && \
    conda clean -yt



