# ==================================================================
# module list
# ------------------------------------------------------------------
# python        3.6    (apt)
# opencv        latest (git)
# caffe         latest (git)
# ==================================================================

FROM nvidia/cuda:9.0-cudnn7-devel
RUN sudo apt-get update
RUN  sudo apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      git \
      libgoogle-glog-dev \
      libgtest-dev \
      libiomp-dev \
      libleveldb-dev \
      liblmdb-dev \
      libopencv-dev \
      libopenmpi-dev \
      libsnappy-dev \
      libprotobuf-dev \
      openmpi-bin \
      openmpi-doc \
      protobuf-compiler \
      python-dev \
      python-pip

RUN  sudo pip install \
      future \
      numpy \
      protobuf

RUN sudo apt-get install -y --no-install-recommends libgflags-dev


RUN git clone --recursive https://github.com/caffe2/caffe2.git && cd caffe2 &&\
	mkdir build && cd build && cmake .. && sudo make install
