FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \
         libgoogle-glog-dev \
         libprotobuf-dev \
         protobuf-compiler \
         libnccl2=2.0.5-2+cuda8.0 \
         libnccl-dev=2.0.5-2+cuda8.0 \
         libjpeg-dev \
         libpng-dev &&\
     rm -rf /var/lib/apt/lists/*


ENV PYTHON_VERSION=3.6
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda create -y --name caffe2-py$PYTHON_VERSION python=$PYTHON_VERSION numpy pyyaml scipy \
     ipython mkl pandas jupyter ipykernel && \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/envs/caffe2-py$PYTHON_VERSION/bin:$PATH

RUN pip install --upgrade pip && \
    pip install protobuf && \
    conda clean -yt

RUN git clone --recursive https://github.com/caffe2/caffe2.git && cd caffe2 &&\
	make && cd build && make install &&\
	python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"

WORKDIR /workspace
RUN chmod -R a+w /workspace