FROM deepc/base:p36-cuda9-cudnn7-devel

RUN apt-get update && apt-get install -y --no-install-recommends \
        openmpi-bin \
        libpng-dev \
        libtiff-dev \
		libjasper-dev && \
    	rm -rf /var/lib/apt/lists/*


ENV KMP_DUPLICATE_LIB_OK TRUE

RUN pip install --upgrade pip && \
    pip install tensorflow-gpu==1.6.0rc0 && \
    pip install https://cntk.ai/PythonWheel/GPU/cntk-2.4-cp36-cp36m-linux_x86_64.whl && \
    pip install keras==2.1.4
    conda clean -yt
